added modules (app, core, features)
MobileUpLLC/MobileUp-Android-Template pull request #1
Opened 2022-04-25 15:38 UTC by developer-kaczmarek

2022-04-26 10:10 UTC, aartikov requested changes

2022-04-26 10:10 UTC, aartikov commented on app/src/main/kotlin/ru/mobileup/template/App.kt
> +val Application.koin get() = (this as App).koin
I think we should use `KoinProvider` interface. It will be helpful for some special cases such as injection to `FirebaseMessagingService`.

`KoinProvider` should be places in `core` module.

2022-04-26 10:10 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/utils/AwaitilityUtils.kt
> + */
Lets remove the part of comment: `You should be careful because function used "pollInSameThread" with conditions that wait forever (or a long time) since Awaitility cannot interrupt the thread when it's using the same thread as the test.`

I think nobody in their right mind will try to do heavy operations in a `condition` body.

2022-04-26 10:10 UTC, aartikov commented on build.gradle
> +    id 'io.gitlab.arturbosch.detekt' version '1.18.1' apply false
Can we declare plugins in the version catalog?

2022-04-26 10:10 UTC, aartikov commented on core/build.gradle
> +    releaseImplementation libs.replica.devtools.release
Maybe we can remove `replica.devtools` here, because it is initialized in the app module.

2022-04-26 10:10 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/error_handling/ApplicationException.kt
> + */
Lets translate in English

2022-04-26 10:10 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/message/ui/NoOverlapByMessageModifier.kt
> +fun Modifier.noOverlapByMessage(): Modifier = composed {
Lets comment what this modifier do.

2022-04-26 10:10 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/message/ui/RealMessageComponent.kt
> +        private const val ShowTime = 4000L
ShowTime -> SHOW_TIME according to code style.

2022-04-26 10:10 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/network/ErrorInterceptor.kt
> +class ErrorInterceptor : Interceptor {
We don't need `ErrorInterceptor` because we use `ErrorHandlingCallAdapter`

2022-04-26 10:10 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/network/NetworkApiFactory.kt
> +    fun <T : Any> createApi(clazz: Class<T>): T {
I think we need `createAuthorizedApi` and `createUnauthorizedApi` and some fake `AuthorizationInterceptor`.

2022-04-26 10:10 UTC, aartikov commented on core/src/main/res/values/strings.xml
> +    <string name="common_retry">Повторить</string>
Lets translate in English

2022-04-26 10:10 UTC, aartikov commented on features/src/main/res/values/pokemons_strings.xml
> +    <string name="pokemons_title">Покемоны</string>
`pokemons_title` - unused

2022-04-26 10:10 UTC, aartikov commented on settings.gradle
> +            version('sesame', '1.4.0-beta1')
1.5.0 is a new stable version

2022-04-26 10:10 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/utils/MockServerBaseUrlProvider.kt
> +class MockServerBaseUrlProvider(private val mockServerRule: MockServerRule) : BaseUrlProvider {
Can we remove `ExperimentalCoroutinesApi` here and in `MockServerRule`?

2022-04-26 10:10 UTC, aartikov commented on app/build.gradle
> +        freeCompilerArgs += "-Xopt-in=kotlin.time.ExperimentalTime"
Please, check if some of freeCompilerArgs are not required

2022-04-27 16:13 UTC, developer-kaczmarek commented on build.gradle
> +    id 'io.gitlab.arturbosch.detekt' version '1.18.1' apply false
Unfortunately, I did not find such a solution

2022-04-28 07:10 UTC, developer-kaczmarek commented on core/build.gradle
> +    releaseImplementation libs.replica.devtools.release
`replica.devtools` is specified in the DI-file of the `core` module

2022-04-28 10:53 UTC, merged