Migrate from LocalizedString to MokoResources
MobileUpLLC/MobileUp-Android-Template pull request #14
Opened 2023-02-08 14:59 UTC by EgoriusE

2023-02-08 15:41 UTC, aartikov requested changes

2023-02-08 15:41 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/template/core/error_handling/ErrorMessage.kt
> +        is SSLHandshakeException -> StringDesc.Resource(R.string.error_ssl_handshake)
SSLHandshakeException из KMM-шаблона мы удалили, там не было нормального способа его отловить. Тут он тоже нигде не создается. Давай, удалим и эксепшен и error_ssl_handshake

2023-02-08 15:41 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/template/core/utils/StringDescUtils.kt
> +) = ResourceFormattedStringDesc(StringResource(resourceId), args.asList())
Круто! Я думал, придется подключать плагин и ссылаться на строки через `MR`, а у тебя гораздо лучше получилось.

2023-02-08 15:41 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/template/core/utils/ReplicaUtils.kt
> +    return stateFlow
Давай, добавим вычисляемые свойства из файла Computed.kt. Они точно пригодятся на реальном проекте для декларативной логики. Там за одно и подтянется `ComponentContext.componentScope`, он оптимизированный - не создает новый скоуп на каждый чих.
 
Можно отдельным МР-ом сделать.

2023-02-22 04:38 UTC, EgoriusE commented on core/src/main/kotlin/ru/mobileup/template/core/utils/ReplicaUtils.kt
> +    return stateFlow
Добавил в https://github.com/MobileUpLLC/MobileUp-Android-Template/pull/15

2023-02-22 07:48 UTC, merged