Added fake component generation plugin
MobileUpLLC/MobileUp-Android-Template pull request #29
Opened 2024-11-25 20:18 UTC by Krakozaybr

См. README.md

2024-11-25 20:42 UTC, Garvardinho commented on .live-plugins/fake-component/README.md
> +    * его имя содержит в себе строку "Component" (см. fakes.Config.isComponent для изменения логики)
Давай для всех мест, где встречается что-то, связанное с кодом/пэкэджем будем делать форматирование кодом через \`вот такие кавычки\`

2024-11-25 20:42 UTC, Garvardinho commented on .live-plugins/fake-component/fakes/Config.kt
> +    private const val StandardDialogControlPackage = "ru.mobileup.ai_drawing.core.dialog.standard.StandardDialogControl"
Давай тогда путь сменим на константу, чтобы менять можно было в одном месте сразу

2024-11-25 20:42 UTC, Garvardinho commented on .live-plugins/fake-component/fakes/Config.kt
> +                FqName("ru.mobileup.ai_drawing.core.dialog.standard.fakeStandardDialogControl")
И тут тогда эту константу-путь тоже применим

2024-11-25 20:42 UTC, Garvardinho commented on .live-plugins/fake-component/fakes/codegen/api/typing/ParsedType.kt
> +    val isParametrized get() = appliedGenerics.isNotEmpty()
_optional:_ isParamet**e**rized

2025-02-28 07:44 UTC, aartikov requested changes

2025-02-28 07:44 UTC, aartikov commented on .live-plugins/fake-component/configs/common/CommonPackages.kt
> +val GlobalScopePackage = "kotlinx.coroutines.GlobalScope"
Предлагаю убрать "Package" в названиях или заменить на "Class"

2025-02-28 07:44 UTC, aartikov commented on .live-plugins/fake-component/configs/common/CommonPackages.kt
> +val PluginConfig.FakeStandardDialogControlPackage
Предлагаю убрать "Package" в названиях. Ведь "$appPackage.core.utils.LoadableState" это не пакет, а класс.

2025-02-28 10:43 UTC, merged