added unit tests and fixed bug on LceWidget
MobileUpLLC/MobileUp-Android-Template pull request #3
Opened 2022-05-04 14:18 UTC by developer-kaczmarek

2022-05-04 16:19 UTC, developer-kaczmarek commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonListComponentTest.kt
> +        mockServerRule.server.enqueue(MockResponse().setResponseCode(404))
При работе с Replica и списком элементов не работают тесты, когда первым состоянием идет ошибка. Аналогичные тесты работают если объект один. В чем может быть причина?

2022-05-11 15:00 UTC, aartikov requested changes

2022-05-11 15:00 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonListComponentTest.kt
> +        val koin = koinTestRule.testKoin()
Не заменили BaseUrlProvider, значит идет обращение к реальному серверу. Наверное, это нехорошо.

2022-05-11 15:00 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonListComponentTest.kt
> +    fun `sends output when type click`() {
```sends output``` - но при нажатии на тип не отправляется аутпут.

При нажатии на тип меняется подсвеченная таба. И что более важно - грузится список других покемонов.

2022-05-11 15:00 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonListComponentTest.kt
> +        mockServerRule.server.enqueue(MockResponse().setResponseCode(404))
Пока не смог понять, нужно дебажить.

2022-05-11 15:00 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/DI.kt
> +    single { ReplicaClient() }
Плохо, что убран NetworkConnectivityProvider. Без него реплики не будут перезагружаться при появлении интернета. Нужно сделать фейковую реализацию для тестов.

2022-05-11 15:00 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/network/ErrorHandlingCall.kt
> +            is DeserializationException -> throwable
```is DeserializationException -> throwable``` для чего понадобилось добавить эту строчку?

2022-05-11 15:00 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/widget/LceWidget.kt
> +        data != null -> content(data, loading)
Такая реализация дает не лучший UX. Но, давай, в отдельном МР-е это исправим.

2022-05-11 15:00 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonDetailsComponentTest.kt
> +    fun `shows error when loader failed`() {
loader -> loading

2022-05-11 15:00 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonDetailsComponentTest.kt
> +@Config(manifest = Config.NONE)
`@Config(manifest = Config.NONE)` - давай, удалим, если не нужно

2022-05-11 15:00 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonDetailsComponentTest.kt
> +        val data = DetailedPokemon(
data - лучше переименовать в expectedData и перенести ниже в блок Assert

2022-05-12 08:44 UTC, developer-kaczmarek commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonListComponentTest.kt
> +    fun `sends output when type click`() {
Временно удалила данный тест, решила его переработать, на получение обновленного списка, пока не работает как нужно, ищу причину

2022-05-12 08:46 UTC, developer-kaczmarek commented on core/src/main/kotlin/ru/mobileup/core/network/ErrorHandlingCall.kt
> +            is DeserializationException -> throwable
При получении ошибки в `ErrorHandlingConverter`, она оборачивается в `DeserializationException`, в последствии ошибка попала в метод `mapToFailureException` и была обернута в UnknownException, что не совсем верно

2022-05-12 09:24 UTC, aartikov requested changes

2022-05-12 09:24 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/pokemons/PokemonDetailsComponentTest.kt
> +            single<NetworkConnectivityProvider> { FakeAndroidNetworkConnectivityProvider() }
Регистрацию FakeAndroidNetworkConnectivityProvider лучше переместить в testKoin, чтоб не дублировать во всех тестах

2022-05-12 09:24 UTC, aartikov commented on app/src/test/kotlin/ru/mobileup/template/utils/FakeAndroidNetworkConnectivityProvider.kt
> +class FakeAndroidNetworkConnectivityProvider : NetworkConnectivityProvider {
Можно переименовать в FakeNetworkConnectivityProvider

2022-05-12 09:46 UTC, aartikov approved these changes

2022-05-12 09:46 UTC, merged