Fix/ux and detekt
MobileUpLLC/MobileUp-Android-Template pull request #4
Opened 2022-05-13 12:11 UTC by developer-kaczmarek

2022-05-16 13:35 UTC, aartikov requested changes

2022-05-16 13:35 UTC, aartikov commented on app/lint-config.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Файл дублируется в app, core и features. Мы можем устранить дублирование?

2022-05-16 13:35 UTC, aartikov commented on app/src/main/kotlin/ru/mobileup/template/App.kt
> +        initDebugTools()
ReplicaDevTools тоже относится к отладочным штукам, поэтому можно ее инициализацию перенести в initDebugTools

2022-05-16 13:35 UTC, aartikov commented on core/src/debug/kotlin/ru/mobileup/core/DebugToolsInitializer.kt
> +    var chuckerCollector: ChuckerCollector? = null
Нужно вызывать chuckerCollector.onError из ErrorHandlingCall.

2022-05-16 13:35 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/theme/Color.kt
> +val primaryDark = Color(0XFF4718E8)
Прежние имена были лучше. Можем не переименовывать их?

2022-05-16 13:35 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/widget/RefreshingProgress.kt
> +                .height(8.dp)
8.dp - по-моему, получилась слишком большая высота. Давай, оставим значение по-умолчанию.

2022-05-16 13:35 UTC, aartikov commented on gradle.properties
> +android.enableJetifier=true
Давай, добавим коммент: required for me.nemiron.hyperion:logs

2022-05-16 13:35 UTC, aartikov commented on core/src/debug/kotlin/ru/mobileup/core/DebugToolsInitializer.kt
> +object DebugToolsInitializer {
Нужна еще и release-реализация

2022-05-17 14:33 UTC, aartikov requested changes

2022-05-17 14:33 UTC, aartikov commented on app/build.gradle
> +    implementation libs.compose.tooling
libs.compose.tooling точно нужен для релизной сборки?

2022-05-17 14:33 UTC, aartikov commented on core/src/main/kotlin/ru/mobileup/core/error_handling/ApplicationException.kt
> +class NoInternetException(cause: Throwable? = null) : TransportException(cause)
Может, сделать cause ненулабельным везде, где получится? И нужно в качестве cause передавать исходный эксепшен при мапинге.

2022-05-17 14:33 UTC, aartikov commented on core/src/release/kotlin/ToolsInitializer.kt
> +        chuckerCollector = ChuckerCollector(
Я думаю, можно вообще не создавать chuckerCollector для релизной сборки

2022-05-17 14:33 UTC, aartikov commented on core/src/debug/kotlin/ru/mobileup/core/ToolsInitializer.kt
> +object ToolsInitializer {
Название DebugToolsInitializer мне нравилось больше. Debug tools обозначает "инструменты для отладки". Просто "инструменты" - не так понятно.

2022-05-17 14:56 UTC, developer-kaczmarek commented on app/build.gradle
> +    implementation libs.compose.tooling
При попытке запустить релизную сборку, android studio откажется запускать с ссылкой на tooling, поэтому внесла соответствующие изменения

2022-05-17 15:03 UTC, merged